FROM scratch

ENV APP_PORT=3080
ENV METRICS_PORT=3088

COPY ledlighter /ledlighter

HEALTHCHECK --interval=30s --timeout=3s \
    CMD curl -f http://localhost:${APP_PORT}/healthz || exit 1

EXPOSE $APP_PORT
EXPOSE $METRICS_PORT

ENTRYPOINT ["/ledlighter"]
