# vi: ft=helm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ledlighter.fullname" . }}-config
  labels:
    {{- include "ledlighter.labels" . | nindent 4 }}
data:
  config.yaml: |
  {{- with .Values.appConfig }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
