# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2
project_name: ledlighter
dist: ../dist/
env_files:
  gitlab_token: ~/nope
  gitea_token: ~/nope
release:
  github:
    owner: xenos76
    name: ledlighter
before:
  hooks:
    - go mod tidy
    - go test
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.appVersion={{.Version}} -X main.buildDate={{.Date}}
archives:
  - formats: ["zip", "tar.gz"]
    name_template: >-
      {{ .ProjectName }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end }}
dockers:
  - image_templates:
      - "ghcr.io/xenos76/{{ .ProjectName }}:{{ .Tag }}-amd64"
    use: buildx
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/xenOs76/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/xenOs76/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
    goarch: amd64
    dockerfile: "../Dockerfile.goreleaser"
  - image_templates:
      - "ghcr.io/xenos76/{{ .ProjectName }}:{{ .Tag }}-arm64"
    use: buildx
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/xenOs76/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/xenOs76/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
    goarch: arm64
    dockerfile: "../Dockerfile.goreleaser"
docker_manifests:
  - name_template: "ghcr.io/xenos76/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/xenos76/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/xenos76/{{ .ProjectName }}:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/xenos76/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/xenos76/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/xenos76/{{ .ProjectName }}:{{ .Tag }}-arm64"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
